<?php

/**
 * @file
 * File containing d_p_side_tiles module.
 */

declare(strict_types = 1);

use Drupal\d_p_side_tiles\Entity\SideTiles;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function d_p_side_tiles_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['d_p_side_tiles'])) {
    $bundles['paragraph']['d_p_side_tiles']['class'] = SideTiles::class;
  }
}
