<?php

/**
 * Implements hook_install().
 */
function d_demo_install() {
  if (\Drupal::moduleHandler()->moduleExists('d_social_media')) {
    $config = \Drupal::configFactory()->getEditable('d_social_media.settings')
      ->set('link_facebook', 'https://www.facebook.com/dropticacom/')
      ->set('link_twitter', 'https://twitter.com/droptica')
      ->set('link_youtube', 'https://www.youtube.com/channel/UCL_XD86NqAJppzw3w7QJqGw')
      ->set('link_instagram', 'https://www.instagram.com/droptica/')
      ->set('link_linkedin', 'https://www.linkedin.com/company/2947414')
      ->save();
    }
}
