<?php

/**
 * @file
 * d_demo module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_content_structure_alter().
 */
function d_demo_content_structure_alter(&$structure, $context) {
  $path = drupal_get_path('module', 'd_demo') . '/pages';
  if ($context == 'all') {
    $structure['homepage'] = ['file' => "$path/homepage.yml"];
    $structure['invest'] = ['file' => "$path/invest.yml", 'link' => 'Invest', 'weight' => 0];
    $structure['product'] = ['file' => "$path/product.yml", 'link' => 'Product', 'weight' => 10];
    $structure['documentation'] = ['file' => "$path/documentation.yml", 'link' => 'Docs', 'weight' => 20, 'children' => [
      'shortcodes' => ['file' => "$path/shortcodes.yml", 'link' => 'Shortcodes', 'weight' => 0],
      'd_p_banner' => ['file' => "$path/d_p_banner.yml", 'link' => 'Banner Paragraph', 'weight' => 10],
      'd_p_form' => ['file' => "$path/d_p_form.yml", 'link' => 'Form Paragraph', 'weight' => 20],
      'd_p_text_blocks' => ['file' => "$path/d_p_text_blocks.yml", 'link' => 'Text Blocks Paragraph', 'weight' => 30],
      'd_p_sidebar_image' => ['file' => "$path/d_p_sidebar_image.yml", 'link' => 'Sidebar Image Paragraph', 'weight' => 40],
      'd_p_subscribe' => ['file' => "$path/d_p_subscribe.yml", 'link' => 'Subscribe File Paragraph', 'weight' => 50],
      'd_p_text' => ['file' => "$path/d_p_text.yml", 'link' => 'Text Paragraph', 'weight' => 60],
      'd_p_text_bg' => ['file' => "$path/d_p_text_bg.yml", 'link' => 'Text With Background Paragraph', 'weight' => 70],
      'd_p_counters' => ['file' => "$path/d_p_counters.yml", 'link' => 'Counters Paragraph', 'weight' => 80],
      'd_p_gallery' => ['file' => "$path/d_p_gallery.yml", 'link' => 'Gallery Paragraph', 'weight' => 90],
      'd_p_carousel' => ['file' => "$path/d_p_carousel.yml", 'link' => 'Carousel Paragraph', 'weight' => 90],
      'd_p_embed' => ['file' => "$path/d_p_embed.yml", 'link' => 'Side Embed Paragraph', 'weight' => 100],
      'd_p_tiles' => ['file' => "$path/d_p_tiles.yml", 'link' => 'Tiles Paragraphs', 'weight' => 110],
    ]];
    $structure['contact'] = ['file' => "$path/contact.yml", 'link' => 'Contact', 'weight' => 30];
  }
}


/**
 * Implements hook_form_alter().
 */
function d_demo_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  switch ($form_id) {
    case 'contact_message_feedback_form':
      unset($form['actions']['preview']);
      foreach ($form as &$formElement) {
        if (isset($formElement['#type'])) {
          switch ($formElement['#type']) {
            case 'text':
            case 'textfield':
            case 'email':
              $formElement['#attributes']['placeholder'] = $formElement['#title'];
              $formElement['#title_display'] = 'invisible';
              break;
            case 'item':
            case 'container':
              if (!empty($formElement['widget']['#title'])) {
                $title = $formElement['widget']['#title'];
                $formElement['widget'][0]['value']['#attributes']['placeholder'] = $title;
                $formElement['widget'][0]['value']['#title_display'] = 'invisible';
              }
              break;
          }
        }
      }

      // Add wrapper for name and mail field.
      $wrapper = [
        '#type' => 'container',
        '#weight' => -666,
        '#attributes' => [
          'class' => ['name-and-mail'],
        ],
      ];

      $wrapper['name'] = $form['name'];
      $wrapper['mail'] = $form['mail'];
      $form['name_and_mail'] = $wrapper;
      unset($form['name']);
      unset($form['mail']);

      break;
  }
}
