info:
    type: d_product
    title: 'TurboX 63 Z 50'
field_d_product_media:
    type: media_image
    directory: demo
    files: [{ path: d_product_init/asset9.jpg, alt: 'Title / Subtitle' }]
body:
    type: text
    data: 'Performance-driven engine with enhanced airflow and combustion efficiency.'
field_product_categories:
    type: taxonomy
    data: { vid: d_product_categories, terms: ['Car Engines'] }
field_tags:
    type: taxonomy
    data: { vid: tags, terms: [Engines, Car] }
field_d_product_link:
    type: cta
    data: { link: null, text: 'Buy now' }
