info:
    type: d_product
    title: 'UrbanZ 35 Edge'
field_d_product_media:
    type: media_image
    directory: demo
    files: [{ path: d_product_init/asset5.png, alt: 'Title / Subtitle' }]
body:
    type: text
    data: 'Sleek engine design with noise-reduction technology for a quieter ride.'
field_product_categories:
    type: taxonomy
    data: { vid: d_product_categories, terms: ['Car Engines'] }
field_tags:
    type: taxonomy
    data: { vid: tags, terms: [Engines, Car] }
field_d_product_link:
    type: cta
    data: { link: null, text: 'Buy now' }
