info:
    type: d_product
    title: 'MarineForce 24 Sport'
field_d_product_media:
    type: media_image
    directory: demo
    files: [{ path: d_product_init/boatasset1.jpg, alt: 'Title / Subtitle' }]
body:
    type: text
    data: 'Innovative engine with state-of-the-art technology for optimal power output.'
field_product_categories:
    type: taxonomy
    data: { vid: d_product_categories, terms: ['Boat Engines'] }
field_tags:
    type: taxonomy
    data: { vid: tags, terms: [Engines, Boat] }
field_d_product_link:
    type: cta
    data: { link: null, text: 'Buy now' }
