field.field.node.content_page.field_page_section:
  add:
    dependencies:
      config:
        - field.field.node.content_page.field_meta_tags
      module:
        - media_library
        - metatag
    settings:
      handler: 'default:paragraph'
      handler_settings:
        target_bundles:
          d_mautic: d_mautic
        target_bundles_drag_drop:
          d_mautic:
            weight: 25
            enabled: true

user.role.d_editor:
  add:
    dependencies:
      config:
        - paragraphs.paragraphs_type.d_mautic
      module:
        - content_translation
        - contextual
        - filter
        - geysir
        - node
        - paragraphs
        - system
        - taxonomy
        - toolbar
