<?php

/**
 * @file
 * Contains d_paragraphs.module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_theme().
 */
function d_p_theme($existing, $type, $theme, $path) {
  return [
    'field__field_d_main_title' => [
      'base hook' => 'field',
    ],
    'field__field_d_subtitle' => [
      'base hook' => 'field',
    ],
    'd_button_link' => [
      'render element' => 'element',
      'variables' => [
        'title' => NULL,
        'options' => NULL,
        'url' => NULL,
      ],
    ],
  ];
}

/**
 * Returns responsive style ids.
 *
 * @return string[]
 *   Array of responsive style ids.
 */
function d_p_responsive_style_ids() {
  // @todo should the helpers be a class?
  $styles_ids = [
    'responsive_image_2000',
    'responsive_image_768',
    'responsive_image_992',
    'responsive_image_1200',
    'responsive_image_1600',
    'responsive_image_2000',
  ];

  return $styles_ids;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function d_p_field_widget_form_alter(&$element, FormStateInterface $form_state, &$context) {
  $field_definition = $context['items']->getFieldDefinition();

  if ($field_definition instanceof FieldConfig) {
    $config = $field_definition->id();
    [, $bundle, $field_name] = explode('.', $config);

    // Make the content of the CKEditor centred by default for the specified
    // paragraph types.
    // @todo Adjust to CKEditor 5
    // d_p_centered_ckeditor_widget_content(
    // $element,
    // $form_state,
    // $context,
    // $bundle);
    // Add default value to the link class attribute.
    if ($field_name === 'field_d_cta_link' &&
      empty($element['url']['#default_value']) &&
      empty($element['options']['attributes']['class']['#default_value'])
    ) {
      if (in_array($bundle, ['d_p_group_of_counters'])) {
        $default_value = 'btn btn-secondary';
      }
      else {
        $default_value = 'btn btn-primary';
      }
      $element['options']['attributes']['class']['#default_value'] = $default_value;
    }
  }
}
