<?php

/**
 * @file
 * Contains d_p_side_embed module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\d_p\Helper\ParagraphModifiersHelper;
use Drupal\d_p\Plugin\Field\FieldWidget\SettingsWidget;

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_side_embed_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();
  $paragraph_modifiers_helper = new ParagraphModifiersHelper($paragraph);
  switch ($bundle) {
    case 'd_p_side_embed':
      $embed_side = $paragraph_modifiers_helper->getModifier(SettingsWidget::PARAGRAPH_SETTING_EMBED_LAYOUT);
      // Process embed side.
      $variables['embed_side'] = $embed_side ? $embed_side : 'left';

      // Process embed code.
      $field_embed = $paragraph->get('field_d_embed')->get(0);
      if ($field_embed) {
        $embed = $field_embed->getValue();
        $variables['embed'] = $embed['value'];
      }

      $variables['embed_side_attributes'] = new Attribute();
      $variables['content_side_attributes'] = new Attribute();
      $variables['content_fields_attributes'] = new Attribute();
      $variables['d_p_side_embed_wrapper_attributes'] = new Attribute();

      break;
  }

  $variables['#attached']['library'][] = 'd_p_side_embed/d_p_side_embed';
}

/**
 * Implements hook_theme().
 */
function d_p_side_embed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_side_embed' => [
      'base hook' => 'paragraph',
    ],
  ];
}
