<?php

/**
 * @file
 * Contains d_p_side_embed module.
 */

use \Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_side_embed_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'd_p_side_embed':
      // Process embed side.
      $field_embed_side = $paragraph->get('field_d_p_si_image_side')->get(0);
      if ($field_embed_side) {
        $embed_side = $field_embed_side->getValue();
        $variables['embed_side'] = $embed_side['value'];
      }

      // Process embed code.
      $field_embed = $paragraph->get('field_d_embed')->get(0);
      if ($field_embed) {
        $embed = $field_embed->getValue();
        $variables['embed'] = $embed['value'];
      }

      $variables['embed_side_attributes'] = new Attribute();
      $variables['content_side_attributes'] = new Attribute();
      $variables['content_fields_attributes'] = new Attribute();
      $variables['d_p_side_embed_wrapper_attributes'] = new Attribute();

      break;
  }

  $variables['#attached']['library'][] = 'd_p_side_embed/d_p_side_embed';
}

/**
 * Implements hook_theme().
 */
function d_p_side_embed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_side_embed' => [
      'base hook' => 'paragraph',
    ],
  ];
}
