core.entity_view_display.paragraph.d_p_group_of_text_blocks.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_d_text_blocks_cta:
          children:
            - field_d_cta_link
          parent_name: ''
          weight: 5
          format_type: html_element
          region: content
          format_settings:
            id: ''
            classes: ''
            element: '<none>'
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
          label: 'Call to Action'
        group_d_text_blocks_content:
          children:
            - field_d_media_icon
            - field_d_main_title
            - field_d_long_text
          parent_name: ''
          weight: 0
          format_type: html_element
          region: content
          format_settings:
            id: ''
            classes: ''
            element: '<none>'
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
          label: Basic
core.entity_view_display.paragraph.d_p_single_text_block.default:
  delete_value:
    - parents: third_party_settings:field_group:group_d_block_content:children
      values:
        - field_d_cta_link
  add:
    third_party_settings:
      field_group:
        group_d_block_cta:
          children:
            - field_d_cta_link
          parent_name: ''
          weight: 3
          format_type: html_element
          region: content
          format_settings:
            id: ''
            classes: ''
            element: '<none>'
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
          label: 'Call To Action'
    content:
      field_d_cta_link:
        weight: 2
