<?php

/**
 * @file
 * Initialization of content for d_blog module.
 *
 * d_blog_init module.
 */

/**
 * Alter content structure.
 * Implements hook_content_structure_alter()
 *
 * @param $structure
 *  The array with structure.
 *
 * @param $context
 *  Which structure array is this?
 */
function d_blog_init_content_structure_alter(&$structure, $context) {
  $path = drupal_get_path('module', 'd_blog_init') . '/pages';

  if ($context == 'all') {
    $structure['blog_post_1'] = ['file' => "$path/post_1.yml"];
    $structure['blog_post_2'] = ['file' => "$path/post_2.yml"];
    $structure['blog_post_3'] = ['file' => "$path/post_3.yml"];
    $structure['blog_post_4'] = ['file' => "$path/post_4.yml"];
    $structure['blog_post_5'] = ['file' => "$path/post_5.yml"];
  }
}

