core.entity_form_display.paragraph.d_p_carousel_item.default:
  change:
    expected:
      content:
        field_d_cta_link:
          type: link_default
    new:
      content:
        field_d_cta_link:
          type: link_attributes
