<?php

/**
 * Implements hook_theme.
 */
function d_social_media_theme($existing, $type, $theme, $path) {
  return [
    'social_media_theme' => [
      'template' => 'social_media',
      'variables' => [
        'show' => false,
        'links' => [],
      ],
    ],
   ];
}

/**
 * Implements hook_block_structure_alter().
 */
function d_social_media_block_structure_alter(&$structure, $context) {
  if ($context == 'all') {
    $path = drupal_get_path('module', 'd_social_media') . '/content/blocks';
    $structure['d_social_media_example'] = ['file' => "$path/d_social_media_example.yml"];
  }
}
