<?php

/**
 * @file
 * Contains d_lang_dropdown module.
 */

declare(strict_types = 1);

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_block_view_alter().
 */
function d_lang_dropdown_block_view_alter(array &$build, BlockPluginInterface $block) {
  if (isset($build['#base_plugin_id']) && $build['#base_plugin_id'] == 'language_block') {
    $build['#attached']['library'][] = 'd_lang_dropdown/d_lang_dropdown';
  }
}
