<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments().
 */
function d_p_help_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'd_p_help/droopler';
}

/**
 * Implements hook_help().
 */
function d_p_help_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.d_p_help':
      $output = '<h3>' . t('Droopler') . '</h3>';
      $output .= '<p>' . t('More info about Droopler - <a href=":link">See official Droopler website</a>.', [':link' => 'https://droopler.com/']) . '</p>';
      $output .= '<h3>' . t('Support') . '</h3>';
      $output .= '<p>' . t('Do You need support with Droopler? -  <a href=":link">Droptica.com</a>.', [':link' => 'https://droptica.com']) . '</p>';
      $output .= '<h3>' . t('Github') . '</h3>';
      $output .= '<p>' . t('Droopler on Github -  <a href=":link">https://github.com/droptica/droopler_project</a>.', [':link' => ' https://github.com/droptica/droopler_project']) . '</p>';
      return $output;
 }
}