<?php

/**
 * @file
 * d_content_init module.
 */

use Drupal\node\Entity\Node;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Save node with paragraphs.
 *
 * @param array $node_to_create
 *   Array node with paragraph content.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function d_content_init_save_node($node_to_create) {

  $node = Node::create([
    'type' => $node_to_create['type'],
    'title' => $node_to_create['title'],
  ]);

  if (isset($node_to_create['field_page_section']['paragraphs'])) {
    foreach ($node_to_create['field_page_section']['paragraphs'] as $paragraph_data) {
      $paragraph = d_content_init_fill_paragraph($paragraph_data);
      $node->field_page_section->appendItem($paragraph);
    }
    $node->save();
  }
}

/**
 * Save an entity.
 *
 * @param $entity_to_create
 *  Array with entity.
 * @param $entity_type
 *  Entity type.
 * @param $uuid
 *  UUID of entity.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function d_content_init_save_entity($entity_to_create, $entity_type, $uuid) {
  $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
  $entity = $storage->create($entity_to_create + ['uuid' => $uuid]);
  $entity->save();
}

/**
 * Save menu items.
 *
 * @param $links
 *  Array of links.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function d_content_init_save_menu($links) {
  foreach ($links as $nid => $item) {
    $menu_link = MenuLinkContent::create([
      'title' => $item['title'],
      'link' => ['uri' => 'internal:/node/' . $nid],
      'menu_name' => 'main',
      'weight' => $item['weight'],
    ]);
    $menu_link->save();
  }
}

/**
 * Fill the paragraph.
 *
 * @param array $paragraph_data
 *  Array with paragraph content.
 *
 * @return \Drupal\Core\Entity\EntityInterface|\Drupal\paragraphs\Entity\Paragraph
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function d_content_init_fill_paragraph($paragraph_data) {
  $paragraph = Paragraph::create([
    'type' => $paragraph_data['paragraph_type'],
  ]);

  foreach ($paragraph_data['data'] as $field_name => $value) {
    switch ($value['type']) {
      case 'text':
      case 'text_long':
        $paragraph->set($field_name, $value['data']);
        $paragraph->$field_name->format = 'full_html';
        break;
      case 'text_select':
        $paragraph->set($field_name, $value['data']);
        break;
      case 'cta':
        $paragraph->set($field_name, [
          'title' => $value['data']['text'],
          'uri' => $value['data']['link'],
        ]);
        break;
      case 'file':
      case 'image':
        $image = file_get_contents(drupal_get_path('module', 'd_content_init') . '/assets/' . $value['data']);
        $image = file_save_data($image, 'public://' . $value['data'], FILE_EXISTS_REPLACE);
        $paragraph->$field_name->appendItem($image);
        break;
      case 'paragraph_reference':
        foreach ($value['data'] as $child) {
          // @TODO fix this ugly fix of incorrect structure in array
          if($field_name == 'field_d_p_tb_block_reference') {
            $new_child['data'] = $child;
            $new_child['paragraph_type'] = 'd_p_single_text_block';
            $child_paragraph = d_content_init_fill_paragraph($new_child);
            $paragraph->$field_name->appendItem($child_paragraph);
          }
        }
        break;
      case 'entity_reference':
        $paragraph->set($field_name, $value['data']);
        break;
    }
  }

  $paragraph->save();
  return $paragraph;
}
