<?php

/**
 * Implements hook_preprocess_field() for HTML document templates.
 */
function d_commerce_product_preprocess_field(&$variables) {
  if ($variables['field_name'] == 'field_product_images') {
    $variables['#attached']['library'][] = 'd_commerce_product/d_product_commerce_slider';
    $slider = views_embed_view('commerce_product_images', 'block_1');
    $variables['slider'] = render($slider);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Remove title block from commerce product page.
 *
 * @see hook_preprocess_HOOK()
 */
function d_commerce_product_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $no_title_routes = ['entity.commerce_product.canonical'];
  if (in_array($route_name, $no_title_routes) && !isset($variables['node'])) {
    foreach ($variables['page']['content'] as &$element) {
      if (isset($element['#plugin_id']) && $element['#plugin_id'] == 'page_title_block') {
        $element['#access'] = FALSE;
      }
    }
  }
}
