<?php

/**
 * Implements hook_preprocess_field() for HTML document templates.
 */
function d_commerce_product_preprocess_field(&$variables) {
  if ($variables['field_name'] == 'field_product_images') {
    $variables['#attached']['library'][] = 'd_commerce_product/d_product_commerce_slider';
    $slider = views_embed_view('commerce_product_images', 'block_1');
    $variables['slider'] = render($slider);
  }
}
