<?php

/**
 * @file
 * Contains d_p_side_by_side module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\d_p_side_by_side\Entity\SideBySide;

/**
 * Implements hook_entity_info_alter().
 */
function d_p_side_by_side_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'paragraph' && !empty($fields['field_d_p_sbs_items'])) {
    /** @var \Drupal\field\Entity\FieldConfig $field */
    $field = $fields['field_d_p_sbs_items'];
    $field->addConstraint('AllItemsRequired', [
      'number' => $field->getFieldStorageDefinition()->getCardinality(),
      'name' => $field->label(),
    ]);
  }
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function d_p_side_by_side_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['d_p_side_by_side'])) {
    $bundles['paragraph']['d_p_side_by_side']['class'] = SideBySide::class;
  }
}
