<?php

/**
 * @file
 * Contains d_paragraphs.module..
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_side_image_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  $styles_ids = d_p_responsive_style_ids();

  switch ($bundle) {

    case 'd_p_side_image':
      $field_image_side = $paragraph->get('field_d_p_si_image_side')->get(0);
      if ($field_image_side) {
        $image_side = $field_image_side->getValue();
        $variables['image_side'] = $image_side['value'];
        d_p_generate_image_set($variables, $styles_ids, $bundle);
      }
      break;

  }
}

/**
 * Implements hook_theme().
 */
function d_p_side_image_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_side_image' => [
      'base hook' => 'paragraph',
    ],
  ];
}