<?php

/**
 * @file
 * Contains d_paragraphs.module..
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_side_image_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {

    case 'd_p_side_image':
      $field_image_side = $paragraph->get('field_d_p_si_image_side')->get(0);
      if ($field_image_side) {
        $image_side = $field_image_side->get('value')->getValue();
        $wrapper_attributes = [
          'class' => [
            'image-side-' . $image_side,
          ],
        ];
        $variables['d_p_side_image_attributes'] = new Attribute($wrapper_attributes);

        switch ($image_side) {
          case 'left-wide':
          case 'right-wide':
            $variables['image_class'] = 'col-md-6 col-lg-7';
            $variables['text_class'] = 'col-md-6 col-lg-5';
            break;

          case 'left':
          case 'right':
          default:
            $variables['image_class'] = $variables['text_class'] = 'col-md-6';
            break;
        }
      }
      break;
  }

  $variables['#attached']['library'][] = 'd_p_side_image/d_p_side_image';
}

/**
 * Implements hook_theme().
 */
function d_p_side_image_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_side_image' => [
      'base hook' => 'paragraph',
    ],
  ];
}
