<?php

/**
 * @file
 * Install, update, and uninstall functions for d_commerce.
 */

/**
 * Implements hook_install().
 */
function d_commerce_install() {
  \Drupal::service('d_content_init.config_update')
    ->importConfigs('d_commerce', '/config/optional', '/block\.block/');
}

/**
 * Implements hook_uninstall().
 */
function d_commerce_uninstall() {
  \Drupal::service('d_content_init.config_update')
    ->deleteConfigs('d_commerce', '/config/optional', '/block\.block/');
}
