<?php

/**
 * @file
 * D_commerce module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\GeneratedLink;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function d_commerce_theme($existing, $type, $theme, $path) {
  return [
    'commerce_checkout_order_summary' => [
      'template' => 'd_commerce-checkout-order-summary',
    ],
    'commerce_order_total_summary__default' => [
      'template' => 'commerce-order-total-summary--default',
      'base hook' => 'commerce_order_total_summary',
    ],
    'commerce_coupon_redemption_form' => [
      'template' => 'd_commerce-coupon-redemption-form',
    ],
    'commerce_checkout_completion_register' => [
      'template' => 'commerce-checkout-completion-register',
      'base hook' => 'commerce_checkout_completion_register',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function d_commerce_theme_suggestions_commerce_order_total_summary_alter(array &$suggestions, array $variables) {
  $suggestions[] = $variables['theme_hook_original'] . '__' . $variables['order_entity']->bundle();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d_commerce_preprocess_commerce_cart_block(&$variables) {
  // Remove original cart icon.
  $variables['icon'] = NULL;

  // Regenerate cart link with button classes.
  $options = [
    'attributes' => ['class' => ['btn btn-primary']],
  ];
  $variables['links'] = [
    [
      '#type' => 'link',
      '#title' => t('Cart'),
      '#url' => Url::fromRoute('commerce_cart.page', [], $options),
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function d_commerce_form_commerce_checkout_flow_multistep_default_alter(&$form, &$form_state, $form_id) {
  if (
    isset($form['actions']['next']['#suffix']) &&
    $form['actions']['next']['#suffix'] instanceof GeneratedLink
  ) {
    $form['actions']['next']['#suffix']->setGeneratedLink(str_replace(
      'link--previous',
      'link--previous btn btn-light',
      $form['actions']['next']['#suffix']->getGeneratedLink()
    ));
  }

  $step = $form['#step_id'] ?? '';

  if ('login' === $step) {
    if (isset($form['login']['returning_customer']['forgot_password'])) {
      $form['login']['returning_customer']['forgot_password']['#attributes'] = [
        'class' => [
          'btn',
          'btn-outline-primary',
          'ml-3',
        ],
      ];
    }
  }
}

/**
 * Set d_customer role for created user.
 *
 * Implements hook_ENTITY_TYPE_insert().
 */
function d_commerce_user_insert(EntityInterface $entity) {
  $entity->addRole('d_customer');
  $entity->save();
}
