<?php

/**
 * Implements hook_theme().
 */
function d_blog_theme($existing, $type, $theme, $path) {
  return [
    'node__blog_post' => [
      'base hook' => 'node',
    ],
    'node__view__blog_listing' => [
        'base hook' => 'node',
    ],
    'paragraph__d_p_blog_image' => [
        'base hook' => 'paragraph',
    ],
    'field__node__field_blog_main_image__blog_post' => [
      'base hook' => 'field',
    ],
    'page__blog' => [
      'base hook' => 'page',
    ],
    'page__taxonomy__term' => [
      'base hook' => 'page',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d_blog_preprocess_paragraph(&$variables) {
    $paragraph = $variables['paragraph'];
    $paragraph_type = $paragraph->getType();
    switch ($paragraph_type) {
        case 'd_p_blog_image':
            $paragraph_has_field_image_full_width = $paragraph->hasField('field_d_p_blog_image_full_width');
            if($paragraph_has_field_image_full_width) {
                $field_blog_image_full_width = $paragraph->get('field_d_p_blog_image_full_width')->get(0);
                $image_on_full_screen_width = $field_blog_image_full_width->getValue()['value'];
                if($image_on_full_screen_width) {
                    $variables['image_on_full_screen_width'] = $image_on_full_screen_width;
                }
            }
            break;
    }
}

/**
 * Implements hook_preprocess_links().
 */
function d_blog_preprocess_links(&$variables) {
    if (isset($variables['links']['node-readmore'])) {
        $variables['links']['node-readmore']['link']['#title'] = t('READ ARTICLE...');
    }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @TODO Change preprocessing images only for blog node pages
 */
function d_blog_preprocess_image(&$variables) {
  $attributes = &$variables['attributes'];

  foreach (array('width', 'height') as $key) {
    unset($attributes[$key]);
    unset($variables[$key]);
  }
}