<?php

/**
 * @file
 * File containing d_p_tiles module.
 */

declare(strict_types = 1);

use Drupal\d_p\Enum\ParagraphSettingTypes;
use Drupal\d_p\Plugin\Field\FieldType\ConfigurationStorage;

/**
 * Implements hook_preprocess_field().
 */
function d_p_tiles_preprocess_field(&$variables) {
  if ($variables['element']['#entity_type'] != 'paragraph') {
    return;
  }

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['element']['#object'];

  if ($variables['element']['#bundle'] !== 'd_p_tiles') {
    return;
  }

  // @todo Fix "move to field formatter".
  if ($variables['field_name'] == 'field_d_media_image') {
    $setting_field = ConfigurationStorage::getSettingsFieldFromEntity($paragraph);
    $featured_images = $setting_field->getSettingValue(ParagraphSettingTypes::TILES_FEATURED_IMAGES);
    $featured_images = empty($featured_images) ? [] : explode(',', (string) $featured_images);

    $featured_images = array_map('intval', $featured_images);
    foreach ($featured_images as $image_number) {
      if ($image_number > 0 && !empty($variables['items'][$image_number - 1])) {
        $variables['items'][$image_number - 1]['content']['#view_mode'] = 'tiles_gallery_fullscreen_featured';
      }
    }
  }
}

/**
 * Implements hook_d_p_centered_ckeditor_widget_paragraphs().
 */
function d_p_tiles_d_p_centered_ckeditor_widget_paragraphs(array &$paragraph_types) {
  $paragraph_types[] = 'd_p_tiles';
}
