<?php

/**
 * @file
 * File containing Gallery Paragraph module.
 */

/**
 * Implements hook_theme().
 */
function d_p_gallery_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_gallery' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_d_image__d_p_gallery' => [
      'base hook' => 'field',
    ]
  ];
}

/**
 * Implements hook_d_p_placeholder_alter().
 */
function d_p_gallery_d_p_placeholder_alter(array &$paragraph_list) {
  $a=2;
}