<?php

/**
 * @file
 * File containing Gallery Paragraph module.
 */

/**
 * Implements hook_theme().
 */
function d_p_gallery_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_gallery' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_d_image__d_p_gallery' => [
      'base hook' => 'field',
    ]
  ];
}

/**
 * Implements hook_d_p_placeholder_alter().
 */
function d_p_gallery_d_p_placeholder_alter(array &$paragraph_list, $paragraphs_entity) {
  if ($paragraphs_entity->bundle() == 'd_p_gallery') {
    $title = $paragraphs_entity->get('field_d_main_title');
    $title = isset($title->getValue()[0]['value']) ? $title->getValue()[0]['value'] : NULL ;
    $background = d_p_get_background_link($paragraphs_entity);
    $paragraph_list[$paragraphs_entity->id()] = [
      'title' => $title,
      'icon' => isset($background) ? $background : '/' . drupal_get_path('module', 'd_p') . '/images/d_p_gallery.png'];
  }
}
