core.entity_form_display.paragraph.d_p_group_of_counters.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_tabs:
          children:
            - group_basic
            - group_i
            - group_set
          parent_name: ''
          weight: 0
          format_type: tabs
          region: content
          format_settings:
            id: ''
            classes: ''
            direction: horizontal
          label: Tabs
        group_basic:
          children:
            - field_d_main_title
            - field_d_media_background
            - field_d_media_icon
            - field_d_long_text
            - field_d_cta_link
          parent_name: group_tabs
          weight: 10
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: open
            required_fields: true
          label: Basic
        group_i:
          children:
            - field_d_counter_reference
          parent_name: group_tabs
          weight: 11
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: closed
            required_fields: true
          label: Items
        group_set:
          children:
            - field_d_settings
          parent_name: group_tabs
          weight: 12
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: closed
            required_fields: true
          label: Settings

  change:
    expected:
      content:
        field_d_counter_reference:
          weight: 6
          settings:
            edit_mode: open
        field_d_cta_link:
          weight: 7
        field_d_long_text:
          weight: 4
        field_d_main_title:
          weight: 2
        field_d_media_icon:
          weight: 1

    new:
      content:
        field_d_counter_reference:
          weight: 5
          settings:
            edit_mode: closed
        field_d_cta_link:
          weight: 6
        field_d_long_text:
          weight: 5
        field_d_main_title:
          weight: 2
        field_d_media_icon:
          weight: 4

core.entity_form_display.paragraph.d_p_single_counter.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_tabs:
          children:
            - group_basic
            - group_settings
          parent_name: ''
          weight: 0
          format_type: tabs
          region: content
          format_settings:
            id: ''
            classes: ''
            direction: horizontal
          label: Tabs
        group_basic:
          children:
            - field_d_number
            - field_d_main_title
            - field_d_media_icon
          parent_name: group_tabs
          weight: 7
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: open
            required_fields: true
          label: Basic
        group_settings:
          children:
            - field_d_settings
          parent_name: group_tabs
          weight: 8
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: closed
            required_fields: true
          label: Settings

  change:
    expected:
      content:
        field_d_main_title:
          weight: 1
        field_d_number:
          weight: 0
        field_d_settings:
          weight: 2

    new:
      content:
        field_d_main_title:
          weight: 2
        field_d_number:
          weight: 1
        field_d_settings:
          weight: 3
