<?php

/**
 * @file
 * Contains d_paragraphs_text_blocks.module..
 */

/**
 * Implements hook_theme().
 */
function d_p_text_blocks_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_group_of_text_blocks' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__d_p_single_text_block' => [
        'base hook' => 'paragraph',
    ],
    'field__field_d_p_tb_block_reference' => [
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_preprocess_field().
 */
function d_p_text_blocks_preprocess_field(&$variables) {
  if ($variables['element']['#entity_type'] == 'paragraph') {
    if ($variables['element']['#bundle'] == 'd_p_group_of_text_blocks') {
      if ($variables['field_name'] == 'field_d_p_tb_block_reference') {
        $num_array = $variables['element']['#object']->get('field_d_number')->getValue();
        $variables['column_class'] = 'col-sm-4';
        if (!empty($num_array[0]['value'])) {
          $columns = floor(12 / $num_array[0]['value']);
          $variables['column_class'] = 'col-sm-' . $columns;
        }
      }
    }
  }
}

/**
 * Implements hook_d_p_placeholder_alter().
 */
function d_p_text_blocks_d_p_placeholder_alter(array &$paragraph_list, $paragraphs_entity) {
  if ($paragraphs_entity->bundle() == 'd_p_subscribe_file') {
    $title = $paragraphs_entity->get('field_d_main_title');
    $title = isset($title->getValue()[0]['value']) ? $title->getValue()[0]['value'] : NULL ;
    $background = d_p_get_background_link($paragraphs_entity);
    $paragraph_list[$paragraphs_entity->id()] = [
      'title' => $title,
      'icon' => isset($background) ? $background : '/' . drupal_get_path('module', 'd_p') . '/images/d_p_subscribe_file.png'];
  }

  if ($paragraphs_entity->bundle() == 'd_p_group_of_text_blocks') {
    $title = $paragraphs_entity->get('field_d_main_title');
    $title = isset($title->getValue()[0]['value']) ? $title->getValue()[0]['value'] : NULL ;
    $background = d_p_get_background_link($paragraphs_entity);
    $paragraph_list[$paragraphs_entity->id()] = [
      'title' => $title,
      'icon' => isset($background) ? $background : '/' . drupal_get_path('module', 'd_p') . '/images/d_p_group_of_text_blocks.png'];
  }
}
