core.entity_form_display.paragraph.d_p_side_by_side.default:
  change:
    expected:
      content:
        field_d_settings:
          settings:
            allowed_settings:
              heading_type:
                status: 0
    new:
      content:
        field_d_settings:
          settings:
            allowed_settings:
              heading_type:
                status: 1
