core.entity_view_display.paragraph.d_p_side_by_side.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_d_side_cta:
          children:
            - field_d_cta_link
          parent_name: ''
          weight: 1
          format_type: html_element
          region: content
          format_settings:
            id: ''
            classes: ''
            element: '<none>'
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
          label: 'Call To Action'
        group_d_side_content:
          children:
            - field_d_long_text
            - field_d_media_icon
            - field_d_main_title
          parent_name: ''
          weight: 0
          format_type: html_element
          region: content
          format_settings:
            id: ''
            classes: ''
            element: '<none>'
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
          label: 'Side content'
