<?php

/**
 * @file
 * Contains d_paragraphs.module..
 */

use\Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_side_image_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  $styles_ids = d_p_responsive_style_ids();

  switch ($bundle) {

    case 'd_p_side_image':
      $field_image_side = $paragraph->get('field_d_p_si_image_side')->get(0);
      if ($field_image_side) {
        $image_side = $field_image_side->getValue();
        $wrapper_attributes = [
          'class' => [
            'image-side-' . $image_side['value'],
          ],
        ];
        $variables['d_p_side_image_attributes'] = new Attribute($wrapper_attributes);
        d_p_generate_image_set($variables, $styles_ids, $bundle);
      }
      break;

  }

  $variables['#attached']['library'][] = 'd_p_side_image/d_p_side_image';
}

/**
 * Implements hook_theme().
 */
function d_p_side_image_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_side_image' => [
      'base hook' => 'paragraph',
    ],
  ];
}
