info:
  type: content_page
  title: Services
field_page_section:
  paragraphs:
    -
      paragraph_type: d_p_side_image
      data:
        field_d_main_title:
          type: text
          data: 'Our services'
        field_d_media_background:
          type: media_image
          directory: demo
          files:
            -
              path: d_demo/d_demo_engine_car_5.jpg
              alt: Engine
        field_d_long_text:
          type: text_long
          data: '<p>We offer a wide range of services for our products. Our experienced team of mechanics can help you repair, overhaul and maintain engines for cars, boats, aircrafts and spaceships.</p>'
        field_d_settings:
          type: field_p_configuration_storage
          paragraph_theme: theme-light
          heading_type: h1
          image_side: right
    -
      paragraph_type: d_p_group_of_text_blocks
      data:
        field_d_settings:
          type: field_p_configuration_storage
          paragraph_theme: theme-secondary
          column_count_desktop: 4
          column_count_tablet: 2
          column_count_mobile: 1
          full-width: 1
          with-tiles: 1
          header-into-columns: 1
        field_d_main_title:
          type: text
          data: Services
        field_d_long_text:
          type: text_long
          data: '<p>In DrooplerEngines we not only produce world-class engines but also provide a lot of services related to engines. Check our services dedicated to your industry.</p>'
        field_d_p_tb_block_reference:
          type: paragraph_reference
          subtype: paragraphs_wrapper
          data:
            -
              paragraph_type: d_p_single_text_block
              data:
                field_d_media_background:
                  type: media_image
                  directory: demo
                  files:
                    -
                      path: d_demo/d_demo_tile_boat.jpg
                      alt: Boat
                field_d_main_title:
                  type: text
                  data: 'For boat manufacturers'
                field_d_cta_link:
                  type: cta
                  data:
                    link: 'internal:/boats'
                    text: 'For boat manufacturers'
                    options:
                      type: primary
                field_d_settings:
                  type: field_p_configuration_storage
                  heading_type: h3
            -
              paragraph_type: d_p_single_text_block
              data:
                field_d_media_background:
                  type: media_image
                  directory: demo
                  files:
                    -
                      path: d_demo/d_demo_tile_plane.jpg
                      alt: Aircraft
                field_d_main_title:
                  type: text
                  data: 'For airplane manufacturers'
                field_d_cta_link:
                  type: cta
                  data:
                    link: 'internal:/aircrafts'
                    text: 'For airplane manufacturers'
                    options:
                      type: primary
                field_d_settings:
                  type: field_p_configuration_storage
                  heading_type: h3
            -
              paragraph_type: d_p_single_text_block
              data:
                field_d_media_background:
                  type: media_image
                  directory: demo
                  files:
                    -
                      path: d_demo/d_demo_tile_car.jpg
                      alt: Car
                field_d_main_title:
                  type: text
                  data: 'For car manufacturers'
                field_d_cta_link:
                  type: cta
                  data:
                    link: 'internal:/cars'
                    text: 'For car manufacturers'
                    options:
                      type: primary
                field_d_settings:
                  type: field_p_configuration_storage
                  heading_type: h3
            -
              paragraph_type: d_p_single_text_block
              data:
                field_d_media_background:
                  type: media_image
                  directory: demo
                  files:
                    -
                      path: d_demo/d_demo_tile_spaceship.jpg
                      alt: Spaceship
                field_d_main_title:
                  type: text
                  data: 'For spaceship manufacturers'
                field_d_cta_link:
                  type: cta
                  data:
                    link: 'internal:/spacecrafts'
                    text: 'For spaceship manufacturers'
                    options:
                      type: primary
                field_d_settings:
                  type: field_p_configuration_storage
                  heading_type: h3
    -
      paragraph_type: d_p_group_of_counters
      data:
        field_d_media_background:
          type: media_image
          directory: demo
          files:
            -
              path: d_demo/demo_bg_2.jpg
              alt: 'Abstract Background'
        field_d_main_title:
          type: text
          data: 'Our company in numbers'
        field_d_counter_reference:
          type: paragraph_reference
          subtype: d_p_single_counter
          data:
            -
              field_d_number:
                type: number
                data: 8
              field_d_main_title:
                type: text
                data: Plants
            -
              field_d_number:
                type: number
                data: 21
              field_d_main_title:
                type: text
                data: 'Offices worldwide'
            -
              field_d_number:
                type: number
                data: 2000
              field_d_main_title:
                type: text
                data: Employees
            -
              field_d_number:
                type: number
                data: 15000
              field_d_main_title:
                type: text
                data: 'Products and parts'
        field_d_settings:
          type: field_p_configuration_storage
          paragraph_theme: theme-primary
          column_count_desktop: 4
          column_count_tablet: 2
          column_count_mobile: 1
    -
      paragraph_type: d_p_text_paged
      data:
        field_d_main_title:
          type: text
          data: 'Stay up to date'
        field_d_long_text:
          type: text_long
          data: '<p>Schedule a date and time for your service.</p>'
        field_d_cta_link:
          type: cta
          data:
            link: 'internal:/contact'
            text: 'Contact us'
            options:
              type: primary
        field_d_settings:
          type: field_p_configuration_storage
          column_count_desktop: 12
          column_count_tablet: 12
          column_count_mobile: 12
          text_align: center
field_teaser_media_image:
  type: media_image
  directory: demo
  files:
    -
      path: d_demo/d_demo_engine_car_5.jpg
      alt: Engine
field_teaser_text:
  type: text_long
  data: 'We provide a lot of services related to engines. Check our services dedicated to your industry.'
