<?php

/**
 * Implements hook_update_8001().
 */
function d_product_update_8001(&$sandbox) {
  \Drupal::service('d_update')
    ->updateConfigurations('module/d_product', 'd_product.8001');
}

/**
 * Add metatags defaults to product node.
 */
function d_product_update_8002() {
  \Drupal::service('d_update')->importConfigs([
    'd_product' => [
      'metatag.metatag_defaults.node__d_product' => '',
    ],
  ]);
}
