ui: mocha-bdd
html: test/fixtures/template.html
scripts:
  - build/in-viewport.min.js
browsers:
  - name: chrome
    version: -1..latest
    platform: Windows 2012 R2 # Win 8.1
  - name: firefox
    version: -1..latest
    platform: Windows 2012 R2 # Win 8.1
  - name: ie
    version: 8..11
  - name: safari
    version: 5..latest
  - name: iphone
    version: 6.0..latest
  - name: ipad
    version: 6.0..latest
  - name: android
    version: 4.1..latest
