<?php

namespace Drupal\d_commerce_product\Entity;

use Drupal\commerce_product\Entity\ProductVariation as CommerceProductVariation;
use Drupal\Component\Plugin\Exception\PluginException;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Logger\LoggerChannelTrait;

/**
 * Provides an override for commerce_product product variation entity class.
 *
 * @package Drupal\d_commerce_product\Entity
 */
class DrooplerProductVariation extends CommerceProductVariation {

  use LoggerChannelTrait;

  /**
   * {@inheritDoc}
   */
  public function label(): string {
    if ($this->shouldGenerateTitle()) {
      $label = parent::label();
    }
    else {
      $label = $this->createVariationLabel();
    }

    return $label;
  }

  /**
   * {@inheritDoc}
   */
  public function getTitle() {
    if ($this->shouldGenerateTitle()) {
      $title = parent::getTitle();
    }
    else {
      $title = $this->createVariationLabel();
    }

    return $title;
  }

  /**
   * Returns whether product variation should use autogenerated title.
   *
   * @return bool
   *   Should product variation use autogenerated title.
   */
  public function shouldGenerateTitle(): bool {
    $variationType = $this->getVariationType();
    $generateTitle = FALSE;
    if ($variationType && $variationType->shouldGenerateTitle()) {
      $generateTitle = TRUE;
    }

    return $generateTitle;
  }

  /**
   * Returns variation type of current product variation.
   *
   * @return \Drupal\Core\Entity\EntityInterface
   *   Product variation type.
   */
  protected function getVariationType(): EntityInterface {
    try {
      $variationType = $this->entityTypeManager()
        ->getStorage('commerce_product_variation_type')
        ->load($this->bundle());
    }
    catch (PluginException $e) {
      $this->getLogger('d_commerce_product')->error($e->getMessage());
      $variationType = NULL;
    }

    return $variationType;
  }

  /**
   * Creates variation label based on product and variation name.
   *
   * @return string
   *   Product variation label.
   */
  protected function createVariationLabel(): string {
    return sprintf("%s %s", $this->getProduct()
      ->getTitle(), parent::label());
  }

}
