core.entity_view_display.paragraph.d_p_tiles.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_d_tiles_content:
          children:
            - field_d_long_text
            - field_d_main_title
            - field_d_media_icon
          label: 'Tiles content'
          parent_name: ''
          region: content
          weight: 0
          format_type: html_element
          format_settings:
            classes: ''
            show_empty_fields: false
            id: ''
            element: ''
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
        group_d_tiles_gallery:
          children:
            - field_d_media_image
          label: 'Tiles Gallery'
          parent_name: ''
          region: content
          weight: 1
          format_type: html_element
          format_settings:
            classes: ''
            show_empty_fields: false
            id: ''
            element: ''
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
        group_d_tiles_cta:
          children:
            - field_d_cta_link
          label: 'Call to action'
          parent_name: ''
          region: content
          weight: 2
          format_type: html_element
          format_settings:
            classes: ''
            show_empty_fields: false
            id: ''
            element: ''
            show_label: false
            label_element: h3
            label_element_classes: ''
            attributes: ''
            effect: none
            speed: fast
