<?php

/**
 * @file
 * Contains d_paragraphs_image_background.module..
 */

/**
 * Implements hook_theme().
 */
function d_p_text_with_bckg_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_text_with_bckg' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_d_p_centered_ckeditor_widget_paragraphs().
 */
function d_p_text_with_bckg_d_p_centered_ckeditor_widget_paragraphs(array &$paragraph_types) {
  $paragraph_types[] = 'd_p_text_with_bckg';
}
