<?php


/**
 * @file
 * Contains d_paragraphs_banner.module..
 */

use Drupal\Core\StreamWrapper\PrivateStream;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_banner_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  $styles_ids = d_p_responsive_style_ids();

  switch ($bundle) {
    case 'd_p_banner':
      unset($styles_ids['responsive_image_768']);
      $styles_ids[] = 'responsive_image_768_banner';
      d_p_generate_image_set($variables, $styles_ids, $bundle);
      $variables['#attached']['library'][] = 'd_p_banner/d_p_banner';
      break;
  }
}


/**
 * Implements hook_theme().
 */
function d_p_banner_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_banner' => [
      'base hook' => 'paragraph',
    ],
  ];
}