<?php
/**
 * @file
 * Install, update and uninstall functions for the d_product_init module.
 */

/**
 * Implements hook_install().
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function d_product_init_install() {
  $path = drupal_get_path('module', 'd_product_init') . '/pages';
  $structure = [];
  for($i = 1; $i <= 20; $i++) {
    $structure['product_' . $i] = ['file' => "$path/product_{$i}.yml"];
  }
  d_content_init_add_nodes($structure);
}
