<?php

/**
 * @file
 * Initialization of content for d_blog module.
 *
 * d_blog_init module.
 */

/**
 * Alter content structure.
 * Implements hook_content_structure_alter()
 *
 * @param $structure
 *  The array with structure.
 *
 * @param $context
 *  Which structure array is this?
 */
function d_product_init_content_structure_alter(&$structure, $context) {
  $path = drupal_get_path('module', 'd_product_init') . '/pages';

  if ($context == 'all') {
    $structure = [];
    $structure['product_1'] = ['file' => "$path/post_1.yml"];
    return;
    $structure['product_2'] = ['file' => "$path/post_2.yml"];
    $structure['product_3'] = ['file' => "$path/post_3.yml"];
    $structure['product_4'] = ['file' => "$path/post_4.yml"];
    $structure['product_5'] = ['file' => "$path/post_5.yml"];
    $structure['product_6'] = ['file' => "$path/post_6.yml"];
    $structure['product_7'] = ['file' => "$path/post_7.yml"];
    $structure['product_8'] = ['file' => "$path/post_8.yml"];
    $structure['product_9'] = ['file' => "$path/post_9.yml"];
    $structure['product_10'] = ['file' => "$path/post_10.yml"];
    $structure['product_11'] = ['file' => "$path/post_11.yml"];
    $structure['product_12'] = ['file' => "$path/post_12.yml"];
  }
}

