<?php

/**
 * @file
 * Contains d_paragraphs_text_paged.module..
 */

declare(strict_types = 1);

use Drupal\d_p_text_paged\Entity\TextPaged;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function d_p_text_paged_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['d_p_text_paged'])) {
    $bundles['paragraph']['d_p_text_paged']['class'] = TextPaged::class;
  }
}

/**
 * Implements hook_d_p_centered_ckeditor_widget_paragraphs().
 */
function d_p_text_paged_d_p_centered_ckeditor_widget_paragraphs(array &$paragraph_types) {
  $paragraph_types[] = 'd_p_text_paged';
}
