core.entity_form_display.paragraph.d_p_subscribe_file.default:
  add:
    dependencies:
      module:
        - field_group
    third_party_settings:
      field_group:
        group_tabs:
          children:
            - group_basic
            - group_form_messages
            - group_settings
          parent_name: ''
          weight: 0
          format_type: tabs
          region: content
          format_settings:
            id: ''
            classes: ''
            direction: horizontal
          label: Tabs
        group_basic:
          children:
            - field_d_main_title
            - field_d_media_background
            - field_d_media_icon
            - field_d_long_text
            - field_d_p_sf_additional_info
            - translation
          parent_name: group_tabs
          weight: 20
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: open
            required_fields: true
          label: Basic
        group_form_messages:
          children:
            - field_file_download
            - field_d_p_sf_consent
            - field_d_p_sf_download_button
            - field_d_p_sf_download_page
            - field_d_p_sf_mail_body
          parent_name: group_tabs
          weight: 21
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: closed
            required_fields: true
          label: 'Form & Messages'
        group_settings:
          children:
            - field_d_settings
          parent_name: group_tabs
          weight: 22
          format_type: tab
          region: content
          format_settings:
            id: ''
            classes: ''
            description: ''
            formatter: closed
            required_fields: true
          label: Settings

  change:
    expected:
      content:
        field_d_long_text:
          weight: 3
        field_d_main_title:
          weight: 0
        field_d_media_icon:
          weight: 1
        field_d_p_sf_consent:
          weight: 10
        field_d_p_sf_download_button:
          weight: 9
        field_d_p_sf_download_page:
          weight: 7
        field_d_p_sf_mail_body:
          weight: 8
        field_file_download:
          weight: 4

    new:
      content:
        field_d_long_text:
          weight: 4
        field_d_main_title:
          weight: 1
        field_d_media_icon:
          weight: 3
        field_d_p_sf_consent:
          weight: 6
        field_d_p_sf_download_button:
          weight: 7
        field_d_p_sf_download_page:
          weight: 8
        field_d_p_sf_mail_body:
          weight: 9
        field_file_download:
          weight: 5
