<?php

/**
 * @file
 * File containing d_p_form module.
 */

use Drupal\d_p\Helper\ParagraphModifiersHelper;
use Drupal\d_p\Plugin\Field\FieldWidget\SettingsWidget;

/**
 * Implements hook_options_list_alter().
 */
function d_p_form_options_list_alter(array &$options, array $context) {
  // Personal form makes error.
  if (method_exists($context['fieldDefinition'], 'id')) {
    if ($context['fieldDefinition']->id() == 'paragraph.d_p_form.field_d_forms') {
      unset($options['personal']);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_form_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $paragraph_modifiers_helper = new ParagraphModifiersHelper($paragraph);
  switch ($paragraph->bundle()) {
    case 'd_p_form':
      $placement = $paragraph_modifiers_helper->getModifier(SettingsWidget::PARAGRAPH_SETTING_FORM_LAYOUT);
      $variables['d_p_form_placement'] = $placement  ? $placement  : 'left';
  }
}

/**
 * Implements hook_theme().
 */
function d_p_form_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_form' => [
      'base hook' => 'paragraph',
    ],
  ];
}
