<?php

/**
 * @file
 * Contains d_paragraphs.module..
 */

/**
 * Implements hook_options_list_alter().
 */
function d_p_form_options_list_alter(array &$options, array $context) {
  // Personal form makes error.
  if (method_exists($context['fieldDefinition'], 'id')) {
    if ($context['fieldDefinition']->id() == 'paragraph.d_p_form.field_d_forms') {
      unset($options['personal']);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_form_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'd_p_form':
      $field_form_layout_field = $paragraph->get('field_d_layout_modifier');
      if (!$field_form_layout_field->isEmpty()) {
        $form_side_value = $field_form_layout_field->first()->getValue();
        $variables['d_p_form_placement'] = $form_side_value['value'];
      }
      break;
  }
}

/**
 * Implements hook_theme().
 */
function d_p_form_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_form' => [
      'base hook' => 'paragraph',
    ],
  ];
}
