d_social_media.settings:
  type: config_object
  label: 'D Social Media settings'
  mapping:
    link_facebook:
      type: text
      label: 'Facebook link'
    link_twitter:
      type: text
      label: 'Twitter link'
    link_youtube:
      type: text
      label: 'Youtube link'
    link_instagram:
      type: text
      label: 'Instagram link'
    link_linkedin:
      type: text
      label: 'Linkedin link'
    link_dribbble:
      type: text
      label: 'Dribbble link'
