<?php

/**
 * @file
 * Module file for d_media.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function d_media_theme() {
  return [
    'd_media_video_embed' => [
      'variables' => [
        'attributes' => NULL,
        'spacer_attributes' => NULL,
      ],
    ],
    'd_media_document_embed' => [
      'variables' => [
        'link' => NULL,
        'name' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function d_media_form_editor_image_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Allow upload svg file in ckeditor, if config wysiwyg_upload_svg_disable
  // is null or false.
  $form['fid']['#upload_validators']['file_validate_extensions'] = ['gif png jpg jpeg svg'];
}
