name: drupal-check deprecations

on:
  # Run on all pushes and on all pull requests.
  # Prevent the build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # Allow manually triggering the workflow.
  workflow_dispatch:
 
jobs:
  Verify:
    name: "Verify deprecations by drupal-check tool"

    runs-on: "ubuntu-latest"

    env:
      PHP_VERSION: "7.4"
      DRUPAL_CHECK_PATH: "modules/custom/ themes/custom/"
      DRUPAL_CHECK_IGNORE: "*md,*.css,*.txt,*.info,*interactive_ui/react_slider/js*,*pl-sk/*,*pattern-lab/*,*_twig-components/*"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: composer

      - name: Install drupal-check
        run: composer global require --no-progress --no-suggest --no-scripts --no-plugins --optimize-autoloader mglaman/drupal-check

      - name: Verify drupal-check deprecations
        run: $HOME/.composer/vendor/bin/drupal-check -d -e=${{ env.DRUPAL_CHECK_IGNORE }} ${{ env.DRUPAL_CHECK_PATH }}

